version: '3'

services:
  server-dev:
    container_name: server-dev
    build: 
      context: './src'
      dockerfile: Dockerfile-Dev
    command: npm start
    env_file:
      - ./.env
    environment:
      - API_PORT=$DEV_API_DOCKER_PORT
      - API_LOCAL_PORT=$DEV_API_LOCAL_PORT
    ports:
      - $DEV_API_LOCAL_PORT:$DEV_API_DOCKER_PORT
    expose:
      - $DEV_API_LOCAL_PORT
    volumes:
      - ./src:/app