version: '3'

services:
  server-prod:
    container_name: server-prod
    build: 
      context: './src'
      dockerfile: Dockerfile-Prod
    env_file:
      - ./.env
    environment:
      - API_PORT=$PROD_API_DOCKER_PORT
      - LOCAL_PORT=$PROD_API_LOCAL_PORT
    ports:
      - $PROD_API_LOCAL_PORT:$PROD_API_DOCKER_PORT
    expose:
      - $PROD_API_LOCAL_PORT
    command: npm start
    volumes:
      - ./src:/app